import json
import re
from pathlib import Path

TAXONOMY_DIR = Path(__file__).parent
_DATA_FILE   = TAXONOMY_DIR / "data.json"

# Lazy-loaded full dataset: {year_str: {tag: {p, fc, d}}}
_raw_data: dict[str, dict] | None = None


def _load_raw() -> dict[str, dict]:
    global _raw_data
    if _raw_data is None:
        _raw_data = json.loads(_DATA_FILE.read_text(encoding="utf-8"))
    return _raw_data


def available_years() -> list[int]:
    """Return sorted list of taxonomy years present in data.json."""
    return sorted(int(y) for y in _load_raw())


_manager_cache: dict[int, "TaxonomyManager"] = {}


def taxonomy_for_year(fiscal_year: int) -> "TaxonomyManager":
    """
    Return a cached TaxonomyManager for the best-matching taxonomy year.
    Prefers exact match, then nearest older year, then oldest available.
    """
    years = available_years()
    if not years:
        raise FileNotFoundError(f"Taxonomy data not found: {_DATA_FILE}")
    candidates = [y for y in years if y <= fiscal_year]
    best = max(candidates) if candidates else min(years)
    if best not in _manager_cache:
        _manager_cache[best] = TaxonomyManager(year=best)
    return _manager_cache[best]


class TaxonomyManager:
    """
    Thin wrapper over the pre-built taxonomy/data.json.
    Provides tag validation and filer-count-sorted tag lists.

    data.json is generated by taxonomy/build_data.py from the official
    FASB US-GAAP Excel files. Re-run build_data.py when new taxonomy
    years are downloaded.
    """

    def __init__(self, year: int = 2024):
        raw = _load_raw()
        year_str = str(year)
        if year_str not in raw:
            raise KeyError(f"Year {year} not found in {_DATA_FILE.name}")
        self.year  = year
        # _index: {tag: {prefix, filer_count, deprecated}}
        self._index: dict[str, dict] = {
            name: {
                "prefix":      entry["p"],
                "filer_count": entry["fc"],
                "deprecated":  entry["d"],
            }
            for name, entry in raw[year_str].items()
        }

    def validate(self, tag: str) -> bool:
        """True if the tag exists in this taxonomy version."""
        return tag in self._index

    def info(self, tag: str) -> dict:
        """Returns {prefix, filer_count, deprecated} for a tag, or {} if not found."""
        return self._index.get(tag, {})

    def get_tags(self, candidates: list[str]) -> list[str]:
        """
        Given a list of candidate tag names:
          1. Tags known to this taxonomy in config order (order is authoritative)
          2. Unknown candidates appended as fallbacks (may exist in older filings)
        Config order is preserved because the developer has explicitly ranked tags
        by preference — filer_count reordering breaks fields like cost_of_revenue
        where a company files both CostOfRevenue ($44B) and CostOfGoodsAndServicesSold
        ($49M, a segment figure) and filer_count would pick the wrong one.
        """
        known   = [t for t in candidates if t in self._index]
        unknown = [t for t in candidates if t not in self._index]
        return known + unknown

    def missing(self, candidates: list[str]) -> list[str]:
        """Returns candidates not present in this taxonomy year."""
        return [t for t in candidates if t not in self._index]
